python event_validation/create_event.py \
    --verbose \
    --git_dir . \
    --events_file events_testing.csv \
    --contact_file contacts_testing.csv \
    --md_file table_testing.md \
    --vol_file rota_testing.csv \
    --dqr_url https://dqr.updateMe.com \
    --eval_url https://dqr.updateMe.com \
    --ignore_far \
    --event_name G361581 
