site_name: 'O4 DetChar Event Validation' 
site_description: 'Pages containing info about O4 DetChar event validation.'
site_author: 'Ronaldas Macas'
site_url: 'https://ldas-jobs.ligo.caltech.edu/~ronaldas.macas/devil/'
site_dir: 'website'
repo_url: 'https://git.ligo.org/ronaldas.macas/devil'
repo_name: 'DEVIL repo'
edit_uri: 'edit/main/mkdocs/docs'
copyright: 'Copyright &copy; 2022 University of Portsmouth'

theme:
  name: material_igwn

nav:
  - index.md
  - testing.md
  - training.md
  - ER15.md
  - O4a.md

markdown_extensions:
  - markdown.extensions.codehilite
  - markdown_include.include
