site_name: 'DetChar Event Validation' 
site_description: 'Pages containing info about O4 DetChar event validation.'
site_author: 'Ronaldas Macas'
site_url: 'https://ldas-jobs.ligo.caltech.edu/~ronaldas.macas/eval_website/'
site_dir: 'website'
repo_url: 'https://git.ligo.org/detchar/event-validation'
repo_name: 'EV repo'
edit_uri: 'edit/main/mkdocs/docs'
copyright: 'Copyright &copy; 2023 University of Portsmouth'

theme:
  name: material_igwn

nav:
  - index.md
  - EVforms.md
  - training.md
  - RRT.md
  - ER15.md
  - O4a.md
  - links.md

markdown_extensions:
  - markdown.extensions.codehilite
  - markdown_include.include
