python eval.py \
    --verbose \
    --git_dir /home/jdo86av3c/projects/eval \
    --events_file events_testing.csv \
    --contact_file contacts_testing.csv \
    --md_file table_testing.md \
    --vol_file rota_testing.csv \
    --dqr_url https://dqr.updateMe.com \
    --eval_url https://dqr.updateMe.com \
    --validator 'Liz Truss' \
    --rrt 'Tony Blair' \
    --mitigation 'John Major' \
    --far 0.5 \
    --ignore_far 0 \
    --json G361581.json
